### PR TITLE
This is the version I used for the current XSDB instance

### PR DESCRIPTION
**Pull request by DickyChant**
This is the version that is used for current XSDB frontend instance.

@PKUfudawei Please take over

### CODE REVIEW

**Comment by DickyChant** [comment]
To further set up SSO etc, we need to prepare a PaaS application @ CERN OpenStack. I will illustrate once the PR is merged

**Comment by DickyChant** [comment]
@menglu21 @bbilin

**Comment by bbilin** [comment]
+1

**Comment by bbilin** [comment]
Meng already merged, sorry for missing that :)

**Pull request merged**
